### ISSUE TITLE
SteamDeck 播放卡顿

### ISSUE THREAD

**Issue by xfangfang** [flathub/cn.xfangfang.wiliwili#17]
原因是 mpv 0.38 调整了默认配置：change `--pulse-latency-hacks` default to `yes`

他的本意应该是避免 pulse 16.0 的bug，但是我在 SteamDeck上测试(pulse 17.0)这个选项会导致视频卡顿。

现在有两个解决方案：
1. 暂时回退到旧版本的mpv: https://github.com/flathub/cn.xfangfang.wiliwili/pull/16 我会直接在wiliwili代码里关闭这个选项，等下个版本更新再使用新版本的 mpv
2. 在配置目录写一个文件: `mpv.conf`，内容是 `pulse-latency-hacks=no`

我不确定第二个方案能不能由 flatpak 构建的过程完成，貌似不能，而且万一用户已经设置自定义配置了也很麻烦，所以我准备先临时降级 mpv，你怎么看 @madoka773

**Comment by madoka773** [comment]
我选1

**Comment by xfangfang** [comment]
好的，那我先这么操作啦～
